name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - setuptools
  - zlib
  - zeromq
  - xz
  - tk
  - sqlite
  - readline
  - openssl
  - ncurses
  - libstdcxx-ng
  - libsodium
  - libgcc-ng
  - libffi
  - ld_impl_linux-64
  - jupyter_core
  - ipython_genutils
  - certifi
  - ca-certificates
  - pickleshare
  - pexpect
  - _libgcc_mutex
